### ISSUE TITLE
Panduan penyediaan takrif

### ISSUE THREAD

**Issue by kmubiin** [kmubiin/suaikata#10]
Isu berkecuali dan tak bersandar untuk membantu penyediaan takrif untuk projek ini.

Secara umum, kita anggap kebanyakan kata masukan Inggeris boleh disuaikan dengan kata masukan Melayu yang sama makna. Perkataan-perkataan ini selalunya berbeza ejaan atau sebutan.

| inggeris   | melayu       |
| ---------- | ------------ |
| water      | air          |
| eat        | makan        |
| vocabulary | kosa kata    |
| ...        | ...          |

Namun, bukan semua kata masukan Inggeris dapat disuaikan dengan perkataan jitu atau asli untuk kata masukan Melayu. Perkataan-perkataan ini mungkin mempunyai ejaan yang sama, hanya berbeza sedikit ejaan atau sebutan, atau tidak mempunyai perkataan jitu yang sama makna.

| inggeris   | melayu             |
| ---------- | ------------------ |
| panda      | panda              |
| issue      | isu                |
| spade      | sejenis daun terup |
| ...        | ...                |

Terutama takrif yang bermula dengan 'sesuatu', 'sejenis', 'orang yang...', 'benda yang...' dan seumpamanya mungkin menandakan tidak ada perkataan jitu yang sama makna dalam bahasa Melayu untuk kata masukan Inggeris yang diberi.

Untuk permulaan, cari kata masukan tersebut di [Wikipedia bahasa Melayu][1] atau [Wiktionary bahasa Melayu][2] dan dapatkan takrif terpendek. Takrif harus ditulis pendek selagi boleh. Panjang takrif terpendek adalah *lima perkataan atau kurang*, tetapi ini hanyalah anggaran.

Jika takrif terpendek menggunakan ejaan sama atau hampir sama, pastikan:

* Perkataan itu boleh difahami tanpa huraian panjang, *dan*
* Perkataan itu sudah diguna pakai oleh media tempatan

Jika takrif terpendek tidak dapat memenuhi syarat-syarat di atas, atau takrif terpendek tidak boleh dicari daripada sumber bebas, buat mana-mana satu pilihan:

A. Sediakan takrif dengan sendiri atau bersama ahli (berusaha)
B. Isikan 'tidak ada terjemahan' di ruang takrif (berkecuali)
C. Abaikan dan pilih kata masukan Inggeris yang lain (bertangguh)

Panduan ini mungkin dikemas kini dari semasa ke semasa. Jika ada keraguan tentang panduan penyediaan takrif (*bukan* perbincangan takrif), sila tinggalkan komen di jalur isu ini.

  [1]: https://ms.wikipedia.org/wiki/Laman_Utama
  [2]: https://ms.wiktionary.org/wiki/Laman_Utama

**Comment by kmubiin** [comment]
**Langkah-langkah menyediakan takrif Inggeris-Melayu**

1. Pilih satu kosa kata Inggeris dalam daftar asal daripada sumber.
2. Buka mana-mana kamus Inggeris untuk memahami makna kosa kata.
3. Kumpulkan makna-makna yang sama atau hampir sama, walaupun bidang berlainan.
4. Berdasarkan makna-makna yang didapati, terjemah dan cari kosa kata Melayu yang sesuai.
5. Semak semula makna terjemah.

Buat catatan untuk perbincangan, apabila perlu.

**Comment by kmubiin** [comment]
**Contoh takrif Inggeris-Melayu**

Perkataan `abstract` mempunyai lebih daripada satu makna dan boleh mengandungi 15 makna dalam bahasa Inggeris (sumber: [Abstract defintion and meaning- CED Online][1]). Oh, tidak! Projek ini tidak mahukan makna sebegitu terperinci.

Jika merujuk pada kamus fizikal, sebenarnya `abstract` boleh dikelaskan kepada tiga makna utama dari segi 'adjective', 'noun', 'verb' (kata adjektif, kata nama, kata kerja). Oleh itu, kosa kata Melayu dalam Projek R4 akan membawakan tiga makna juga.

Apabila terjemah diisi di helaian rebak (spreadsheet), `abstract` akan menggunakan tiga baris untuk mengandungi tiga makna seperti berikut:

| inggeris | melayu                          |
| -------- | ------------------------------- |
| ...      | ...                             |
| abstract | abstrak (pemikiran, seni)       | 
| abstract | ringkasan; rumusan	             |
| abstract | meringkaskan; merumuskan; tarik |
| ...      | ...                             |

Perkataan `abstract` adalah yang pertama diterjemah sejak helaian rebak dicipta semalam.


  [1]: https://www.collinsdictionary.com/dictionary/english/abstract

**Comment by raafsmakmal** [comment]
Saya lupa syor supaya terjemahan itu murid sekolah menengah pun boleh faham. Kalau mampu, buat seolah-olah terjemahan boleh difahami murid tingkatan satu. 

Jadi, untuk kes abstract, 'tak zahir' adalah lebih afdal daripada 'abstrak'. Dengan nada yang sama, issue sebagai 'isu' juga lebih sesuai dengan 'masalah' atau 'persoalan'.

**Comment by kmubiin** [comment]
@raafsmakmal 

> Saya lupa syor supaya terjemahan itu murid sekolah menengah pun boleh faham. Kalau mampu, buat seolah-olah terjemahan boleh difahami murid tingkatan satu.

Setuju. Secara tidak langsung, terjemahan yang sesuai boleh diketahui apabila membelek buku-buku rujukan peringkat rendah atau menengah dan kamus-kamus edisi pelajar.

> Jadi, untuk kes abstract, 'tak zahir' adalah lebih afdal daripada 'abstrak'. ...

Boleh masukkan dalam lajur 'terjemah A' di Google Sheets. Mana-mana baris yang mempunyai teks dalam lajur 'terjemah M' dan 'terjemah A' kedua-duanya, akan ditanda dengan mesej 'eh, terjemah dua kali?' dalam lajur 'melayu' di Google Sheets.

Untuk permulaan, isikan sahaja terjemah masing-masing terlebih dahulu. Apabila sudah isi penuh, boleh bincang di isu 'Soal kesesuaian takrif' kemudian.

Nota: Mesej 'eh, terjemah dua kali?' telah disemak semula menjadi 'eh, dua salinan?'

**Comment by kmubiin** [comment]
Lihat tangkapan layar di bawah untuk gambaran sepintas lalu:

![daftar-psat-terjemah-dua-kali](https://user-images.githubusercontent.com/30212524/38129787-0256d01c-3433-11e8-839d-cb24a53eb1be.png)

Misalnya, saya sudah masukkan 'tak zahir' dalam lajur 'terjemah A' di Google Sheets.

Mesej tertulis '[eh, terjemah dua kali?]' akan memudahkan tapisan dan statistik tertulis akan dikemas kini secara auto di helaian '2.selidik' pada bila-bila masa.

**Comment by kmubiin** [comment]
**Pandangan terjemah M**

Saya akan sentiasa gunakan kamus versi British untuk fahamkan kosa kata Inggeris. Sebabnya, sejak beberapa tahun dulu, ada beberapa kali saya tidak jumpa atau tidak setuju dengan definisi yang dibawakan oleh Oxford English Dictionary. Tetapi apabila saya rujuk di Collins English Dictionary, saya jumpa dan faham lebih baik.

Entah kenapa, saya rasakan versi British lebih mudah untuk diikuti.

**Tambahan pada komen asal**

Mungkin ada sebilangan orang akan kata, "Eh, kamus Oxford dan Collins adalah kamus Inggeris British. Kenapa M seolah-olah kata salah satu kamus ini tidak gunakan Inggeris British?"

Benar, kamus Oxford dan Collins adalah kamus Inggeris British. Namun, mengikut pengalaman saya, kamus Oxford memasukkan ejaan yang mencampur adukkan Inggeris British dan Amerika (tidak ingat perkataan mana). Pada masa itu, saya habis pening dan buntu.

Kemudian barulah saya faham, mungkin kamus Oxford memilih perkataan dengan ejaan yang lebih dikenali ramai, tidak kira Inggeris British atau Amerika. Oleh itu, saya jadi agak keliru.

Sejak masa itulah saya pakai kamus Collins yang tidak memberi kekeliruan.

**Comment by kmubiin** [comment]
**Sekiranya menggunakan kamus dwibahasa**

Kamus dwibahasa boleh digunakan untuk mendapatkan cadangan terjemah dan rangsangan untuk mencari terjemah yang lebih baik, tetapi *tidak patut* digunakan selain daripada itu.

Ada tiga masalah yang dikenal pasti: 

1. Kamus dwibahasa akan membawa keraguan terhadap pengetahuan diri yang sedia ada.
2. Kamus dwibahasa mempunyai takrif yang "pelik" (berkaitan dengan 1).
3. Kamus dwibahasa mempunyai takrif yang "sempit", terutama jika gunakan satu kamus sahaja.

Berkenaan masalah 1: Jangan hanya bergantung pada pengetahuan yang sedia ada. Lebih baik rujuk pada kamus bahasa asal (Inggeris) terlebih dahulu. Ini adalah penting untuk fahamkan makna yang dibawakan oleh bahasa asal, sekaligus mengesahkan pengetahuan diri yang sedia ada.

Berkenaan masalah 2: Setelah rujuk pada kamus bahasa asal (Inggeris), barulah rujuk kamus dwibahasa (Inggeris-Melayu) untuk perbandingan. Aturan ini boleh elakkan kekeliruan semasa terjemah.

Berkenaan masalah 3: Gunakan sekurang-kurangnya dua atau lebih kamus dwibahasa. Misalnya, M gunakan empat kamus dwibahasa (terbitan 1996, 1997, 2000, 2004). Terbitan lama mungkin ada cadangan yang tidak dijumpai dalam terbitan baru, dan sebaliknya.

Kesimpulan: Gunakan kamus dwibahasa untuk rangsangan terjemah sahaja.

**Comment by kmubiin** [comment]
**Contoh takrif Inggeris-Melayu melalui perbandingan takrif**

Kosa kata yang hendak diterjemah: `accessible`

Berikut adalah perbandingan takrif menggunakan dua kamus bahasa asal (Inggeris) dan empat kamus dwibahasa (Inggeris-Melayu).

1. Kamus bahasa asal (Inggeris), versi buku:

   > adj. easy to reach

2. Kamus bahasa asal (Inggeris), versi dalam talian:

   > adjective
   > 
   > 1. easy to approach, enter, use, or understand
   > 2. accessible to
   > 3. obtainable; available
   > 4. easy for disabled people to enter or use 
   > ...

3. Kamus dwibahasa (Inggeris-Melayu), terbitan 1996:

   > boleh dilalui.

4. Kamus dwibahasa (Inggeris-Melayu), terbitan 1997:

   > a. dapat diperoleh.

5. Kamus dwibahasa (Inggeris-Melayu), terbitan 2000:

   > adj yang dapat ditempuhi, digunakan;
   > dokumen yang tidak boleh dilihat [...]

6. Kamus dwibahasa (Inggeris-Inggeris-Melayu), terbitan 2004:

   > adj
   > 1. boleh sampai (ke situ); dapat didatangi
   > 2. mudah didapati, digunakan atau difahami

Berikut adalah terjemah M yang telah diisi dalam helaian rebak:

> mudah sampai, capai atau dapat

Kenapa hasil terjemah menjadi sedemikian? Jika boleh faham makna perkataan `accessible` sebanyak mungkin dengan hasil terjemah tersebut, maka tidak perlu diterangkan kenapa. Jika tidak boleh faham, maka perlu dibawa bincang kemudian.

**Comment by kmubiin** [comment]
**Contoh takrif yang dahulukan bahasa mudah**

Berkenaan komen A dan M pada minggu lalu:

> > Saya lupa syor supaya terjemahan itu murid sekolah menengah pun boleh faham. Kalau mampu, buat seolah-olah terjemahan boleh difahami murid tingkatan satu.
> 
> Setuju. [...]

Berikut adalah contoh takrif yang dahulukan bahasa mudah, walaupun kosa kata Inggeris boleh ditakrif menggunakan satu perkataan yang jitu dalam bahasa Melayu:

| inggeris | ke | melayu | di |
| -------- | -- | ------ | -- |
| ambiguous | 1 | tidak jelas makna; taksa | M |
| ... ||||
| apprenticeship | 1 | latihan berguru; perantisan | M |
| ... ||||
| disclaimer | 1 | kenyataan tolak tuntutan; penafian | M |
| ... ||||

Mana-mana satu perkataan yang jitu di atas mungkin tidak boleh difahami dengan sekali baca. Oleh itu, bahasa yang lebih mudah faham telah didahulukan.

**Comment by kmubiin** [comment]
**Gunakan bahasa Melayu piawai**

Wikipedia, ensiklopedia bebas, mempunyai garis panduan Wikipedia bahasa Melayu di laman berikut: [Wikipedia:Gunakan bahasa Melayu piawai][1]. Rencana tersebut agak panjang, jadi saya akan ringkaskan panduan tersebut untuk kegunaan projek ini.

Garis panduan ringkas untuk bahasa Melayu piawai ada tiga perkara utama:

1. Gunakan kosa kata Melayu, jika ada, dan bukan semata-mata kosa kata Melayu yang berbeza ejaan sahaja. Projek R4 harus patuhi perkara ini untuk setiap makna yang *pertama*.

   [X] Salah: `component`: 1. `komponen dalam litar (sains)`; 2. `bahagian`

   [O] Betul: `component`: 1. `bahagian`; 2. `komponen dalam litar (sains)`

2. Gunakan ejaan penuh dan bukan singkatan.

   [X] Salah: `yg`, `drpd`

   [O] Betul: `yang`, `daripada`

3. Gunakan kosa kata Melayu yang sesuai untuk penulisan dan bukan percakapan, sekalipun dengan tujuan gunakan kosa kata mudah yang boleh difahami.

   [X] Salah: `random`: `hentam saja` (ini bukan lawak)

   [O] Betul: `random`: `sembarangan`

Secara tidak langsung, bahasa Melayu piawai adalah bahasa Melayu yang diiktiraf oleh pihak pemantau bahasa (DBP di Malaysia; MABBIM dianggotai Brunei, Indonesia, Malaysia) dan juga yang digunakan oleh penerbit kamus yang disanjung tinggi seperti Oxford Fajar.

Nota 1: Tambah huraian untuk terjemah `component 2.` untuk menunjukkan makna kedua adalah bukan sekadar berbeza ejaan. Juga sama dengan terjemah M dalam helaian rebak.

Nota 2: Pembetulan dibuat berdasarkan komen A; perkataan `tak` dan `tidak` telah dikeluarkan daripada contoh di atas. Perkataan `tak` adalah sah dan bukan jenis singkatan seperti `yg` dan `drpd`.

Nota 3: Tambah huraian untuk perkara 3 untuk menerangkan kenapa perkara ini diketengahkan.


  [1]: https://ms.wikipedia.org/wiki/Wikipedia:Gunakan_bahasa_Melayu_piawai

**Comment by raafsmakmal** [comment]
'eh, dua salinan?' terima kasih mengemaskini helai rebak... 

Sangat setuju "mudah sampai, capai atau dapat" untuk accessible. Padat dan mudah faham.

Tentang https://ms.wikipedia.org/wiki/Wikipedia:Gunakan_bahasa_Melayu_piawai

Setuju point 1 sahaja. Saya turut syor supaya diabaikan terjemahan pinjaman jika perkataan bahasa Melayu 'asas' adalah memadai. Sebagai contoh, perkataan 'komponen' sebagai terjemahan diabaikan terus.

Perkataan 'tak' memang dieja sebagaimana disebut walhal 'yg' dan 'drpd' kehilangan huruf ejaan sebenar. Ejaan 'tak' adalah ejaan sebenar dari masukan yg sebenar - boleh rujuk prpm.dbp.gov.my jika musykil. Keadaan ini berbeza dgn 'yg' dan 'drpd'. 

'Hentam saja' memang terjemahan lemah, asal-usul 'hentam' dengan sendirinya ialah 'memukul'. Oleh itu 'rawak' dan 'rambang' sememangnya terjemahan yang lebih utama. Terjemahan yang kurang memuaskan tak perlu bangkit.

Sebenarnya, ada beberapa terjemahan yg saudara M isikan yg saya kira lebih sesuai daripada yg saya isi. Untuk kes sebegini, saya akan isi semula bahagian saya dgn terjemahan M utk menyatakan persetujuan.

Ada juga terjemahan saudara M yg saya kira saya boleh perbaiki. Untuk kes ini, saya akan isikan bahagian saya dgn sedikit pembetulan yg saya kira lebih sesuai.

**Comment by kmubiin** [comment]
Komen M selepas petikan komen A.

> Perkataan 'tak' memang dieja sebagaimana disebut walhal 'yg' dan 'drpd' kehilangan huruf ejaan sebenar. Ejaan 'tak' adalah ejaan sebenar dari masukan yg sebenar

Betul kata A. Daftar kata adalah sah, malah sudah ada dalam kamus terbitan lama seperti Kamus Bahasa Melayu Edisi Pelajar (1980). Saya akan betulkan komen M di atas.

> Sebenarnya, ada beberapa terjemahan yg saudara M isikan yg saya kira lebih sesuai daripada yg saya isi. Untuk kes sebegini, saya akan isi semula bahagian saya dgn terjemahan M utk menyatakan persetujuan.

Tak perlu isi semula. Isikan tanda pagar `#` di hadapan teks dalam terjemah A sudah memadai. Fungsi kemas kini secara auto akan menukarkan `X2` kepada `M+` apabila terjemah A diabai.

> Ada juga terjemahan saudara M yg saya kira saya boleh perbaiki. Untuk kes ini, saya akan isikan bahagian saya dgn sedikit pembetulan yg saya kira lebih sesuai.

Setelah A isikan terjemah yang lebih baik, giliran saya pula membuat semakan dan isikan tanda pagar `#` di terjemah M saya sendiri.

Gunakan tanda pagar `#` untuk abaikan terjemah masing-masing. Tanda `X2` akan berubah menjadi `M+` atau `A+`, di mana tanda `+` boleh dilihat sebagai tanda sokong. Mudah!

Contoh dalam helaian rebak: lihat baris `chronicle, 1` yang mengandungi tanda `A+`

**Comment by kmubiin** [comment]
**Salah faham imbuhan kata kerja**

Sejak usaha terjemah projek ini dimulakan, sebahagian terjemah M didapati menggunakan kata kerja akhiran '-kan' dan bukan 'me- ... -kan'. Sebabnya, M menganggap kedua-dua penggunaan imbuhan ini masih dalam kategori kata kerja, cuma jimat beberapa aksara dan dalam nada ayat pasif.

Tetapi, kebanyakan kamus tidak menggunakan takrif dengan kata kerja akhiran '-kan' dan [imbuhan kata kerja akhiran '-kan'][1] hanya digunakan untuk melakukan sesuatu kerja untuk orang lain atau suruhan.

* M sudah sedia maklum tentang penggunaan kata kerja akhiran '-kan' sebagai suruhan.

* Kebanyakan kamus hanya boleh mencari kata masukan `mengetepikan` dengan mencari kata akar `tepi` dan kata masukan `menyapukan` dengan mencari kata akar `sapu`.

* Satu-satunya kamus yang menggunakan takrif sedemikian ialah Tesaurus Bahasa Melayu keluaran PTS Professional (2011). Misalnya, boleh cari kata masukan `ketepikan` dan `sapukan` untuk melihat perkataan lain yang berkaitan. Cuma kata masukan jarang dibawakan dalam bentuk ini.

Akhirnya M faham bahawa takrif kata kerja dalam bahasa Melayu mesti menggunakan kata kerja berapitan (awalan dan akhiran bersama). M sudah membuat pembetulan untuk terjemah M sedia ada daripada akhiran '-kan' kepada apitan 'me- ... -kan'.

  [1]: https://ms.wikipedia.org/wiki/Imbuhan_kata_kerja_(bahasa_Melayu)#-kan

**Comment by kmubiin** [comment]
**Keadaan terjemah setakat 3 petang, 19 April 2018 (Khamis)**

Syabas! Tahap pencapaian terjemah sudah mencapai 100% pada sehari dua yang lepas, setelah M mengisi terjemah untuk lapan perkataan terakhir yang ditinggalkan pada minggu lalu. Sekarang dalam usaha menyemak dan memperbaik terjemah sedia ada (terutama M sendiri).

Helaian 'selidik' mempunyai nilai rujukan baru untuk melihat:
* Sebanyak mana kosa kata Inggeris yang ada terjemah panjang (lebih daripada 20 aksara), dan
* Sebanyak mana tanda koma bertitik `;` dan tanda kurungan `(...)` digunakan dalam terjemah.

Keadaan terjemah secara ringkas:

* Penilaian terjemah A adalah *cemerlang*
* Penilaian terjemah M adalah *tidak memuaskan* (kerana banyak terjemah panjang dan salah guna tanda koma bertitik untuk memuatkan makna berbeza dalam satu baris)
* M sedang perbaik terjemah M sendiri

Untuk maklumat lanjut, sila teliti helaian rebak di Google Sheets.
