### ISSUE TITLE
Soal kesesuaian takrif

### ISSUE THREAD

**Issue by kmubiin** [kmubiin/suaikata#11]
Isu ini membawakan ruang pertanyaan dan perbincangan semasa menyediakan takrif.

Contoh-contoh pertanyaan yang mungkin timbul:

* Bagaimana perkataan `panda` diterjemah untuk Inggeris-Melayu? Ini kerana perkataan `panda` menggunakan ejaan sama dalam kedua-dua bahasa.
* Perkataan `vocabulary` ada satu makna, tetapi ada pelbagai perkataan terjemah Melayu `kosa kata`, `perbendaharaan kata`, `vokabulari`, `leksikon`. Pening, mana satu nak pilih?
* Perkataan `screenshot` langsung tidak ada perkataan terjemah Melayu! Nak cari mana?

Untuk penyunting jemputan di Google Sheets, boleh terus tinggalkan komen di mana-mana ruang atau teks di helaian yang tersedia dalam talian.

Untuk permulaan, sila rujuk pada 'Panduan penyediaan takrif' (#10). Jika tidak dinyatakan di pautan tersebut, sila tinggalkan komen di bawah jalur isu ini.

**Penting**: Soal kesesuaian takrif seharusnya timbul dalam tempoh batu penanda Pertengahan (akan berakhir pada 9 April 2018). Jika ada keraguan, sila tinggalkan komen seawal mungkin.

**Comment by raafsmakmal** [comment]
Komen saya, A, dalam italic.

> Bagaimana perkataan panda diterjemah untuk Inggeris-Melayu? Ini kerana perkataan panda menggunakan ejaan sama dalam kedua-dua bahasa.

_Panda sebagai 'beruang panda' sudah memadai. Sudah tiada sebab mana2 kanak-kanak di Malaysia ini tak kenal panda sejak ada di zoo kita._

> Perkataan vocabulary ada satu makna, tetapi ada pelbagai perkataan terjemah Melayu kosa kata, perbendaharaan kata, vokabulari, leksikon. Pening, mana satu nak pilih?

_Menyahut cabaran saudara M tentang buku berserta terjemahan bahasa mudah, kosa kata adalah lebih afdal. Sebab?_

_Dalam banyak2 perkataan yang saudara senaraikan, yang paling berkemungkinan murid sekolah menengah pernah berdepan ialah perkataan 'kosa kata'. Yang kedua paling berkemungkinan ialah 'perbendaharaan kata'. Jadi, bezanya 'perbendaharaan' dan 'kosa'._

_Apa maksud perkataan2 ini? 'Perbendaharaan' itu boleh kita teka2 sebagai benda yang dijaga seorang bendahara - yakni khazanah, atau simpanan harta (Chancellery - Chancellor, kes dekat2 dalam bahasa Inggeris/Eropah). 'Kosa' pula kita dapati di kuasa/perkasa/perkosa yang maknanya (kekuatan) yang menguasai. Dua2 nya bila digabung dengan 'kata' maka jadilah 'simpanan harta perkataan' ataupun 'penguasaan perkataan'. Masuk akal dan 'kena/ngam' sebagai terjemahan vocabulary._

_Walau bagaimanapun, kedua-dua 'kosa' dan 'perbendaharaan' agak sukar difahami murid sekolah dengan sendirinya. Seingat saya perkataan bendahara hanya kita mula mengenal ketika bab kesultanan dalam Sejarah tahap sekolah menengah. Kerana 'kosa' lebih pendek, dan lebih berkemungkinan seorang murid tu kenal akan 'kuasa', 'perkasa' atau 'perkosa' daripada 'bendahara', maka 'kosa kata' lebih afdal._

_Vokabulari dan leksikon - jangankan murid sekolah, orang berpendidikan tinggi pun belum tentu tahu perkataan ni. Abaikan terus._

> Perkataan screenshot langsung tidak ada perkataan terjemah Melayu! Nak cari mana?

_Boleh google - hasilnya tangkapan layar. Jika tiada terjemahan ke bahasa Melayu boleh pilih yang Indonesia. Seperti biasa, utamakan sama ada terjemahan boleh difahami atau tak._ 

---

Nota suntingan M: Perbaik format teks yang dipetik daripada komen asal menggunakan `>` dan masukkan baris baru antara teks yang dipetik dan yang dijawab. Sekarang mudah baca.

**Comment by kmubiin** [comment]
Komen M selepas teks yang dipetik:

>> Perkataan vocabulary ada satu makna, tetapi ada pelbagai perkataan terjemah Melayu kosa kata, perbendaharaan kata, vokabulari, leksikon. Pening, mana satu nak pilih?
>
> Menyahut cabaran saudara M tentang buku berserta terjemahan bahasa mudah [...]

Err... soalan-soalan di atas adalah sekadar contoh dan tidak ditujukan kepada sesiapa untuk dijawab. Tak sangka dijawab kesemuanya. (gelak).

>> Perkataan screenshot langsung tidak ada perkataan terjemah Melayu! Nak cari mana?
>
> Boleh google - hasilnya tangkapan layar. Jika tiada terjemahan ke bahasa Melayu boleh pilih yang Indonesia. Seperti biasa, utamakan sama ada terjemahan boleh difahami atau tak.

Atau lebih mudah, cari artikel ['screenshot' di Wikipedia English][1] dan lihat jika ada artikel terjemahan di ruang bahasa lain (languages). Dan ya, ada artikel terjemahan ['screenshot' dalam bahasa Indonesia][2].

> Cuplikan layar atau tangkapan layar (bahasa Inggris: screenshot, screen capture, atau screen dump) adalah suatu gambar yang diambil oleh komputer untuk merekam tampilan yang tampak di layar atau peranti keluaran visual lainnya [...]

Di situlah saya dapat tahu dan memilih perkataan 'tangkapan layar' dalam isu-isu sebelum ini.


  [1]: https://en.wikipedia.org/wiki/Screenshot
  [2]: https://id.wikipedia.org/wiki/Cuplikan_layar

**Comment by kmubiin** [comment]
**Kesesuaian takrif untuk istilah semasa**

Bukan mudah untuk mendapatkan takrif yang sesuai istilah semasa. Kesesuaian takrif menjadi rumit apabila istilah semasa, terutama dalam bidang teknologi maklumat (IT), tidak boleh didapati dalam kamus mahupun di Wikipedia ensiklopedia bebas dalam bahasa Melayu.

Misalnya, 'suspend' dalam bahasa Inggeris diterjemah menjadi 'gantung' dalam bahasa Melayu. Perkataan ini biasa digunakan dalam kehidupan seharian dan terjemahan adalah mantap.

* Contoh ayat asal (Inggeris): The school has decided to *suspend* the misbehaving students.

* Contoh ayat terjemah (Melayu): Pihak sekolah telah mengambil keputusan untuk *menggantung* pelajar-pelajar yang tidak berkelakuan baik.

Namun, apabila 'suspend' hendak ditakrif dari segi istilah antara muka (user interface) pada komputer, perkataan 'gantung' mungkin dirasakan "pelik" apabila dibaca sepintas lalu.

**Sesuaikah takrif itu**

Dalam hal tersebut, pengguna mahir IT boleh semak pada sistem operasi yang ada sokongan bahasa Melayu. Mana-mana sistem operasi akan menanyakan pengguna sama ada hendak 'log out', 'restart', 'shut down' atau 'suspend' apabila selesai menggunakan komputer.

Tangkapan layar (screenshot) di bawah menunjukkan tetingkap kecil yang dipaparkan oleh antara muka grafik Xfce di sistem operasi GNU/Linux.

![xfce-dialog-box-ms](https://user-images.githubusercontent.com/30212524/38453217-62c5d482-3a84-11e8-825d-aa01b4a2edfa.png)

Jadi, pilihan terjemah untuk 'suspend' ialah 'gantung' (eh, sama rupanya). Pilihan terjemah tersebut mungkin sama atau tidak sama apabila merujuk pada sistem operasi lain seperti Windows atau macOS.

Dalam hal ini, apa yang penting ialah kesesuaian takrif. Walaupun perkataan 'gantung' dirasakan "pelik" pada bacaan pertama, sekiranya ada bukti yang mengatakan perkataan tersebut memang diterima pakai oleh para pengguna, maka boleh dianggap itulah terjemah yang "betul".

**Komen M**

Perkataan 'gantung' memang biasa untuk maksudkan 'gantung sekolah', 'gantung lesen', 'gantung baju' dan seumpamanya. Faham sebagai 'gantung komputer' atau 'gantung sesi'? Pelik. Ada 'gantung sekolah' tapi rasanya tak ada 'gantung kelas'? Entahlah.

P.S.: Komen yang ditinggalkan di Google Sheets telah dibuang dan diterangkan sebetulnya bersama bukti sokongan dalam komen ini.

**Comment by kmubiin** [comment]
**Lanjutan komen M**

Berkenaan komen M sebelum ini:

> Perkataan 'gantung' memang biasa untuk maksudkan 'gantung sekolah', 'gantung lesen', 'gantung baju' dan seumpamanya. Faham sebagai 'gantung komputer' atau 'gantung sesi'? Pelik. Ada 'gantung sekolah' tapi rasanya tak ada 'gantung kelas'? Entahlah.

Perkataan 'gantung' mempunyai kegunaan berikut:

* gantung baju - letakkan baju pada penyangkut
* gantung mati; gantung diri - hukuman atau perbuatan menamatkan hayat seseorang
* gantung sekolah - hukuman tidak dibenarkan hadir ke sekolah
* gantung kelas - hampir sama dengan 'gantung sekolah' (jarang didapati)
* gantung sesi - hampir sama dengan 'gantung sekolah' (jarang didapati)
* gantung tugas - hukuman tidak dibenarkan hadir ke tempat kerja

Untuk memahami takrif istilah komputer 'gantung', ada dua kegunaan yang paling masuk akal: 'gantung baju' dan 'gantung tugas'.

1. Jika kita fahamkan 'sesi semasa komputer' sebagai satu benda atau pemilikan, maka makna 'gantung baju' lebih masuk akal, yakni 'gantung rekod semasa komputer'.

2. Jika kita fahamkan 'sesi semasa komputer' sebagai satu kerja atau perbuatan, maka makna 'gantung tugas' lebih masuk akal, yakni 'gantung tugas semasa komputer'.

Namun begitu, 'gantung tugas' membawa makna 'hukuman' atau 'larangan' menjalankan tugas yang diberi. Ini dirasakan tidak sesuai untuk memahami istilah komputer 'suspend'. Oleh itu, 'gantung baju' adalah satu-satunya takrif yang paling masuk akal.

Meskipun terjemah yang "betul" untuk 'suspend' ialah 'gantung', M berpendapat ada terjemah yang lebih sesuai untuk istilah komputer tersebut:

* Perkataan 'tangguh', yakni hentikan tugas buat sementara waktu, atau;

* Perkataan 'tidurkan', yakni rujukan langsung untuk istilah komputer yang lebih umum '[sleep mode][1]' yang merangkumi semua jenis arahan tidur termasuk 'suspend', 'hibernate', 'hybrid sleep'.

Kesimpulan: Terjemah yang "betul" untuk 'suspend' ialah 'gantung', dan terjemah ini akan digunakan untuk takrif kosa kata dalam Projek R4.


  [1]: https://en.wikipedia.org/wiki/Sleep_mode

**Comment by kmubiin** [comment]
**Semakan kemas kini dan soal kesesuaian takrif**

Tidak ada soalan baru tentang kesesuaian takrif sejak 24 jam yang lalu. Untuk perbincangan terjemah dua kali, isu baru akan dicipta di bawah Rancangan Akhir.

Rancangan Pertengahan berakhir pada hari ini dan isu ini akan ditutup bersama.
