### ISSUE TITLE
Kajian projek tercipta

### ISSUE THREAD

**Issue by kmubiin** [kmubiin/suaikata#2]
Berkaitan dengan #1 

Senarai kamus tercipta di GitHub dan perkamusan di pautan luar:

* [GitHub - DanielAmani/KamusBahasaMelayu][1]
* [GitHub - dolph/dictionary][2]
* [GitHub - adambom/dictionary][3]
* [GitHub - dwyl/english-words][4]
* [Wiktionary - Wiktionary:Public domain sources][5]
* [FOLDOC - Computing Dictionary][6]
* [GitHub - Supported Dictionary Formats · goldendict/goldendict Wiki][7]
* [Custom - Cari Makna Perkataan Bahasa Malaysia][8] melalui [/r/malaysia][9]
* [GitHub - lukluk/database_bahasa][10] melalui carian semula
* [GitHub - andrisetiawan/lexicon][11] melalui carian semula
* [GitHub - matbahasa/MALINDO_Morph][12] melalui carian semula

Carian semula boleh dibuat di GitHub melalui kata kunci ['bahasa melayu'][a], ['kosa kata'][b] dan ['data bahasa'][c]. Mungkin ada projek baru yang muncul dari semasa ke semasa.

Isu ini berkait rapat dengan penggunaan teknologi maklumat. Mungkin agak sukar untuk dibincang dalam bahasa Melayu. Untuk isu ini, boleh tinggalkan komen dalam bahasa Inggeris.

**English may be used for discussing this issue.**

  [1]: https://github.com/DanielAmani/KamusBahasaMelayu
  [2]: https://github.com/dolph/dictionary
  [3]: https://github.com/adambom/dictionary
  [4]: https://github.com/dwyl/english-words
  [5]: https://en.wiktionary.org/wiki/Wiktionary:Public_domain_sources
  [6]: http://foldoc.org/
  [7]: https://github.com/goldendict/goldendict/wiki/Supported-Dictionary-Formats
  [8]: https://makna.online/
  [9]: https://www.reddit.com/r/malaysia/comments/83v6eo/my_simple_project_find_meaning_of_a_malay_word/
  [10]: https://github.com/lukluk/database_bahasa
  [11]: https://github.com/andrisetiawan/lexicon
  [12]: https://github.com/matbahasa/MALINDO_Morph
  [a]: https://github.com/search?utf8=%E2%9C%93&q=bahasa+melayu&type=
  [b]: https://github.com/search?utf8=%E2%9C%93&q=kosa+kata&type=
  [c]: https://github.com/search?utf8=%E2%9C%93&q=data+bahasa&type=

**Comment by raafsmakmal** [comment]
Mohon kongsi halatuju/aspirasi lapangan (field/area) perkataan yang akan kita takrifkan.

**Comment by kmubiin** [comment]
**Perbandingan projek-projek tercipta**

Dari segi lesen dan kemas kini:

| Projek                        | Lesen     | Kemas kini   |
| ----------------------------- | --------- | ------------ |
| DanielAmani/KamusBahasaMelayu | CC0-1.0   | Jun 22, 2016 |
| dolph/dictionary              | ?         | Feb 9, 2017  |
| adambom/dictionary            | MIT, PGL  | Oct 27, 2016 |
| dwyl/english-words            | Unlicense | Mar 14, 2018 |
| makna.online                  | ?         | Mar 12, 2018 |
| FOLDOC                        | ?         | Jan 30, 2018 |
| lukluk/database_bahasa        | ?         | May 20, 2015 |
| andrisetiawan/lexicon         | ?         | Apr 4, 2015  |
| matbahasa/MALINDO_Morph       | CC-BY-4.0 | Mac 13, 2018 |

Mana-mana projek yang tidak dinyatakan lesen dianggap sebagai hak cipta terpelihara dan tidak boleh dipakai semula secara bebas. Tarikh kemas kini adalah benar setakat petang 16 Mac 2018 dan malam 17 Mac 2018.

Dari segi kata masukan:

| Projek                        | Kata masukan | Sumber kiraan       |
| ----------------------------- | -----------: | ------------------- |
| DanielAmani/KamusBahasaMelayu | ~9,700       | abjad{A-E}.html     |
| dolph/dictionary              | 25,322       | popular.txt         |
| adambom/dictionary            | 86,036       | dictionary.json     |
| dwyl/english-words            | 370,098      | words_alpha.txt     |
| makna.online                  | 14,000       | /r/malaysia         |
| FOLDOC                        | ~15,000      | foldoc.org          |
| lukluk/database_bahasa        | 28,526       | tb_katadasar.sql    |
| andrisetiawan/lexicon         | 28,526       | kata_dasar_kbbi.csv |
| matbahasa/MALINDO_Morph       | 100,744      | malindo_dic_*.tsv   |

Antara projek-projek yang tersenarai di atas, hanya FOLDOC merangkumi kosa kata dalam bidang khusus, iaitu bidang perkomputeran. Meskipun satu bidang sahaja, kata masukan mencapai lima angka banyaknya!

Nota 1: Jadual-jadual di atas ada tambahan baris: lukluk/database_bahasa, andrisetiawan/lexicon.

Nota 2: Jadual-jadual di atas ada tambahan baris: matbahasa/MALINDO_Morph

Nota 3: Pembetulan untuk makna.online: ~144,000 -> 14,000 (terlebih satu digit).

@raafsmakmal 
Pada pandangan saya, kita tidak mempunyai hala tuju seperti projek-projek yang tersenarai di atas. Untuk perkataan yang akan kita takrifkan, saya telah tinggalkan komen di jalur "Rangkuman kosa kata".

**Comment by kmubiin** [comment]
**Hasil kajian projek tercipta**

Berdasarkan carian yang saya lakukan sejak 10 hari lepas (9 Mac 2018) hingga hari ini:

* `DanielAmani/KamusBahasaMelayu` adalah satu-satunya projek yang mengusahakan kamus bahasa Melayu sebagai sumber terbuka di GitHub; Projek ini kelihatan tergendala, format data yang digunakan bukan mudah alih (HTML) dan kata masukan tidak lengkap (abjad A-E).
    > Nota 2018-11-17: sumber ini menyerupai format kata masukan Kamus Dewan; barangkali Edisi Keempat sebab ada tambahan kata masukan asing. Walaupun dilesenkan di bawah domain awam (CC0-1.0), sumber ini *tidak wajar* untuk dijadikan rujukan.
* `makna.online` tidak mempunyai sumber terbuka yang boleh diselidik.
* `lukluk/database_bahasa` dan `andrisetiawan/lexicon` adalah senarai kata masukan dalam bahasa Indonesia tanpa makna.
* `matbahasa/MALINDO_Morph` adalah kamus morfologi untuk bahasa Melayu/Indonesia, iaitu jenis kamus yang bukan untuk kegunaan umum.
* Tidak ada satu pun projek tercipta yang masih mengusahakan kamus bahasa Melayu sebagai sumber terbuka di GitHub.

Carian luar membawa saya ke laman [Wikikamus (Wiktionary bahasa Melayu)][1], iaitu projek kamus sumber terbuka oleh Yayasan Wikimedia, bermula 12 Disember 2002. Juga digelar Wikikamus / KamusWiki.

Wikikamus ada menyimpan senarai [sumber untuk penterjemah][2]. Malangnya, kebanyakan pautan luar telah mati dan hanya tinggal dua sumber yang masih hidup:

* [E-istilah - Carian Istilah Anda][3], oleh Universiti Teknologi Malaysia Skudai, dengan kerjasama Dewan Bahasa Dan Pustaka; Merangkumi 5000 Istilah Komputer & 8600 Istilah Kejuruteraan.
* [Istilah IT][4] oleh Sabah Edu.net; Merangkumi lebih 500 istilah IT.

Dari segi lesen, kebanyakan projek-projek tercipta tidak mengikut pelesenan yang disarankan atau tidak dihiraukan langsung. Projek-projek tercipta dilihat tidak ada kecenderungan (trend) ke arah sumber terbuka untuk memudahkan penggunaan semula data.

Dari segi kata masukan, bahasa Melayu tidak mempunyai jumlah kata masukan yang lazim. Projek-projek tercipta hanya mengandungi kata masukan sebanyak mungkin, tetapi tidak lengkap atau tidak mengambil tahu tentang kata masukan yang kerap digunakan.

Kesimpulannya, tidak ada projek tercipta yang mengusahakan kamus bahasa Melayu sebagai sumber terbuka. Dengan itu, kita tidak mempunyai contoh baik yang boleh kita rujuk untuk pembaikan.

Kajian projek tercipta telah selesai dan isu ini boleh ditutup.


  [1]: https://ms.wiktionary.org/wiki/Wiktionary
  [2]: https://ms.wiktionary.org/wiki/Wiktionary:Sumber_untuk_penterjemah
  [3]: http://eddycute.tripod.com/
  [4]: http://www.sabah.edu.my/istilah/
