### ISSUE TITLE
Pelesenan projek

### ISSUE THREAD

**Issue by kmubiin** [kmubiin/suaikata#3]
Projek ini perlu ada lesen yang sesuai untuk kebaikan bersama. Pemilihan lesen untuk Projek R4 perlu dibincang kerana lesen tersebut akan menentukan syarat penggunaan projek.

Definisi Pelesenan^1:

* hal-hal yg berkaitan dgn urusan memberi atau mengeluarkan lesen: lembaga ~." (Kamus Pelajar Edisi Kedua).
* urusan memberi lesen atau meluluskan permohonan lesen: lembaga ~ (Kamus Dewan Edisi Ketiga).

^1: Ejaan 'pelesenan' yang digunakan oleh tajuk isu ini adalah betul. Boleh semak dengan Kamus Dewan atau [carian umum di PRPM][1]. Tetapi [salah satu jawapan khidmat nasihat di PRPM][2] ada membezakan antara 'pelesenan' dan 'perlesenan'. Mengelirukan.

Senarai panduan pelesenan di pautan luar:

* [Choose an open source license][3]
* [Frequently Asked Questions - Creative Commons][4]^2
* [Conformant Licenses - Open Definition][5]
* [Licenses FAQ - Open Data Commons][10]
* [Are Creative Commons licenses suitable for data? - Open Data SE][6]
* [Benefits of using CC0 over CC-BY for data - Open Data SE][11]
* [CC-BY vs MIT or BSD licenses regarding re-use? - Open Data SE][12]
* [Why is CC BY-SA discouraged for code? - Open Source SE][7]
* [Using copyleft licenses for non-programming purposes - Open Source SE][8]

^2: Di bawah tajuk soalan, [Can I combine material under different Creative Commons licenses in my work?][9], ada satu jadual kesesuaian sumber pelbagai lesen. Ini akan disalin semula sebagai jadual menggunakan teks Markdown, dan akan ditinggalkan sebagai komen kemudian.

Isu ini berkait rapat dengan hak cipta. Sumber maklumat dalam bahasa Melayu agak terhad dan menyukarkan perbincangan.  Untuk isu ini, boleh tinggalkan komen dalam bahasa Inggeris.

**English may be used for discussing this issue.**

  [1]: http://prpm.dbp.gov.my/cari1?keyword=pelesenan
  [2]: http://prpm.dbp.gov.my/Cari1?keyword=pelesenan&d=175768&#LIHATSINI
  [3]: https://choosealicense.com/
  [4]: https://creativecommons.org/faq/
  [5]: http://opendefinition.org/licenses/
  [6]: https://opendata.stackexchange.com/q/5995
  [7]: https://opensource.stackexchange.com/q/1717
  [8]: https://opensource.stackexchange.com/q/1810
  [9]: https://creativecommons.org/faq/#can-i-combine-material-under-different-creative-commons-licenses-in-my-work
  [10]: https://opendatacommons.org/faq/licenses/
  [11]: https://opendata.stackexchange.com/q/26
  [12]: https://opendata.stackexchange.com/q/245

**Comment by kmubiin** [comment]
**Perbandingan lesen-lesen sumber terbuka**

Jadual 1: Salinan semula imej [CC_License_Compatibility_Chart.png][1] menggunakan teks Markdown:

|             | PDM | CC0 | CC-BY | CC-BY-SA | CC-BY-NC | CC-BY-ND | CC-BY-NC-SA | CC-BY-NC-ND |
| ----------- | :-: | :-: | :---: | :------: | :------: | :------: | :---------: | :---------: |
| PDM         | O   | O   | O     | O        | O        | X        | O           | X           |
| CC0         | O   | O   | O     | O        | O        | X        | O           | X           |
| CC-BY       | O   | O   | O     | O        | O        | X        | O           | X           |
| CC-BY-SA    | O   | O   | O     | O        | X        | X        | X           | X           |
| CC-BY-NC    | O   | O   | O     | X        | O        | X        | O           | X           |
| CC-BY-ND    | X   | X   | X     | X        | X        | X        | X           | X           |
| CC-BY-NC-SA | O   | O   | O     | X        | O        | X        | O           | X           |
| CC-BY-NC-ND | X   | X   | X     | X        | X        | X        | X           | X           |

Jadual 2: Salinan semula jadual [Recommended conformant licenses][6] menggunakan teks Markdown:

| License      | Domain        | By | SA | Comments                                          |
| ------------ | ------------- | -- | -- | ------------------------------------------------- |
| CC0          | Content, Data | N  | N  | Dedicate to the Public Domain (all rights waived) |
| PDDL         | Data          | N  | N  | Dedicate to the Public Domain (all rights waived) |
| CC-BY-4.0    | Content, Data | Y  | N  |                                                   |
| ODC-BY       | Data          | Y  | N  | Attribution for data(bases)                       |
| CC-BY-SA-4.0 | Content, Data | Y  | Y  |                                                   |
| ODbL         | Data          | Y  | Y  | Attribution-ShareAlike for data(bases)            |

> These licenses conform to the Open Definition and are:
>
> * Reusable: Not specific to an organization or jurisdiction.
> * Compatible: Must be compatible with at least one of GPL-3.0+, CC-BY-SA-4.0, and ODbL-1.0. Permissive/attribution-only licenses must be compatible with all 3 of the aforementioned licenses, and at least one of Apache-2.0, CC-BY-4.0, and ODC-BY-1.0.
> * Current: Widely used and generally considered best practice by a broad spectrum of projects and actors within the domains of applicability of the license.

Nota 1: [Public Domain Mark (PDM)][2] dan [Unlicense][3] menggunakan logo yang hampir sama (huruf 'C' yang mempunyai garis serong melalui titik tengah). Untuk perbandingan lesen domain awam, sila lihat [Public domain equivalent license][4] di Wikipedia (bahasa Inggeris sahaja).

Nota 2: Untuk kemudahan salinan, saya juga telah tampal ~salinan jadual 1 di GitHub Gist~ terpadam

Nota 3: Untuk kemudahan salinan, saya juga telah tampal ~salinan jadual 2 di GitHub Gist~ terpadam


  [1]: https://github.com/creativecommons/faq/blob/master/CC_License_Compatibility_Chart.png
  [2]: https://creativecommons.org/share-your-work/public-domain/pdm/
  [3]: https://unlicense.org/
  [4]: https://en.wikipedia.org/wiki/Public_domain_equivalent_license
  [6]: http://opendefinition.org/licenses/

**Comment by raafsmakmal** [comment]
Bagi saya, MIT dan Apache 2.0 sudah memadai.

**Comment by kmubiin** [comment]
Setahu saya, MIT dan Apache adalah lesen untuk atur cara (source code) dan tidak sesuai untuk data. Pelesenan sebenarnya bergantung pada tujuan dan matlamat projek. Bincang dulu isu lain yang lebih mudah.

**Comment by kmubiin** [comment]
**Cadangan M untuk pelesenan projek**

Berdasarkan kajian projek tercipta, kebanyakan projek tidak menghiraukan isu pelesenan. Penggunaan lesen adalah berbeza dan tidak ada kecenderungan terhadap mana-mana satu lesen yang disarankan.

> Bagi saya, MIT dan Apache 2.0 sudah memadai.

Lesen MIT dan Apache meletakkan syarat atribusi (attribution) dan lesen tersebut sesuai untuk atur cara (source code). Untuk pelesenan data atau kandungan bukan atur cara (data or content), lesen yang disarankan adalah CC-BY-4.0 dan ODC-BY.

Setakat apa yang saya baca dan faham:

* [CC-BY-4.0][1] membolehkan semua kandungan (data and content) dilesenkan sekaligus^1 apabila lesen versi 4.0 digunakan (versi sebelumnya dikatakan tidak merangkumi pelesenan data).
* [ODC-BY][2] membolehkan data atau pangkalan data (data or database) dilesenkan secara berasingan daripada kandungannya (content)^2

^1: Pelesenan kandungan (data and content) dinyatakan secara umum oleh [laman pertimbangan di Creative Commons][3] iaitu "CC licenses are appropriate for all types of content you want to share publicly, except software and hardware." dan dinyatakan secara terangan oleh [jadual saranan di Open Definition][4] dan [panduan pelesenan untuk bukan atur cara di Choose a License][5].

^2: Misalnya, lesen data atau pangkalan data adalah ODC-BY tetapi, sebagai contoh, fail imej yang terdapat dalam pangkalan data boleh menggunakan lesen lain yang membawa syarat tambahan.

Lagi contoh penggunaan lesen:

* [OpenStreetMap mengkaji perbezaan lesen ODbL dan CC-BY-4.0][6].
* [Open energy system database][7] mempunyai jadual ringkas yang membandingkan projek-projek pangkalan data terbuka dan kebanyakan projek menggunakan lesen CC-BY.

Tuntasnya, CC-BY-4.0 adalah lesen yang dicadangkan untuk Projek R4. Syarat penggunaan adalah selari dengan lesen MIT dan Apache, tetapi lesen CC-BY-4.0 adalah lebih sesuai dan terkenal untuk data.

Pembetulan: Cadangan A -> Cadangan M. Silap penama, maaf!


  [1]: https://creativecommons.org/licenses/by/4.0/
  [2]: https://opendatacommons.org/licenses/by/summary/
  [3]: https://wiki.creativecommons.org/wiki/Considerations_for_licensors_and_licensees
  [4]: http://opendefinition.org/licenses/
  [5]: https://choosealicense.com/non-software/
  [6]: https://blog.openstreetmap.org/2017/03/17/use-of-cc-by-data/
  [7]: https://en.wikipedia.org/wiki/Open_energy_system_databases

**Comment by kmubiin** [comment]
> Pembetulan: Cadangan A -> Cadangan M. Silap penama, maaf!

Suntingan dalam komen sebelum ini.

**Comment by raafsmakmal** [comment]
Saya setuju
"Tuntasnya, CC-BY-4.0 adalah lesen yang dicadangkan untuk Projek R4. Syarat penggunaan adalah selari dengan lesen MIT dan Apache, tetapi lesen CC-BY-4.0 adalah lebih sesuai dan terkenal untuk data."
