### ISSUE TITLE
Rangkuman kosa kata

### ISSUE THREAD

**Issue by kmubiin** [kmubiin/suaikata#4]
Berasal daripada #1 

Isu ini akan membincangkan perkara-perkara berikut:

* Kriteria atau cara pemilihan kosa kata
* Mata pelajaran atau bidang yang akan diteroka
* Pecahan kata masukkan daripada jumlah 100-300

Kriteria merujuk pada ciri-ciri yang memudahkan pemilihan kosa kata. Namakan satu kriteria dan jadikan itu sebagai garis panduan apabila meneroka sesuatu bidang. Kriteria itu dianggap baik jika kriteria itu memudahkan pemilihan kosa kata untuk dimasukkan ke dalam koleksi.

Bidang yang akan diteroka tidak terhad pada satu bidang. Namakan mana-mana bidang yang kita mahu teroka. Sebaiknya tetapkan had ikut kemampuan dan minat kita.

Pecahan kata masukan merujuk pada bilangan kata masukan yang dibahagi sama rata atau tidak rata. Pecahan tidak rata boleh dilakukan sekiranya kita ingin kumpul lebih banyak perkataan untuk beberapa bidang tertentu dan lebih sedikit perkataan untuk beberapa bidang selebihnya.

**Comment by kmubiin** [comment]
**Cadangan M untuk rangkuman kosa kata**

Kriteria yang dicadang ialah **kosa kata yang sering diguna pakai**, sama ada dalam talian atau luar talian. Utamakan kosa kata yang sudah ada terjemahan menurut [Pusat Rujukan Persuratan Melayu (PRPM)][1] dan Kamus Dewan Edisi Ketiga atau Edisi Keempat (jika ada).

Bidang yang dicadang ialah bidang-bidang berikut:

* tiga bidang umum (daripada tiga tahap pendidikan)
* dua bidang khusus (mana-mana bidang dengan nama akhiran -an, -i, -gi, -tik)

Untuk bidang umum, kenal pasti kosa kata di tahap rendah (tahun 1 hingga 6), tahap menengah (tingkatan 1 hingga 5), dan tahap tinggi (tingkatan 6, matrikulasi dan ijazah sarjana muda). Tumpuan bersama akan diberi kepada **sains**, **matematik** dan **bahasa Inggeris**.

Untuk bidang khusus, kenal pasti kosa kata dalam dua bidang tertentu. Salah satu bidang yang dicadang ialah **kejuruteraan** (terhad kepada pengalaman kerja di industri pembuatan). Satu lagi bidang akan dipilih dan dibawakan oleh saudara A.

Untuk pecahan kata masukan, secara purata, setiap bidang akan mengandungi 20 hingga 60 kata masukan. Jika mahu lebih pengkhususan, boleh tetapkan had 100 kata masukan untuk bidang umum *secara keseluruhan* dan baki 50 hingga 100 kata masukan untuk bidang khusus *setiap satu*.

Tuntasnya, bidang umum akan dibawakan oleh kedua-dua ahli projek dan bidang khusus akan dibawakan oleh setiap ahli projek satu bidang pilihan.

Pembetulan: Purata asal "10 hingga 30 kata masukan" adalah kiraan salah, sepatutnya 20 hingga 60 kata masukan (pengiraan purata: 100/5 = 20; 300/5 = 60).

Nota 1: Cadangan ini ada keraguan dan perlu dipermudah.


  [1]: http://prpm.dbp.gov.my/

**Comment by raafsmakmal** [comment]
"Kosa kata yang sering diguna pakai"

Saya setuju. Dalam pengalaman saya, perkataan bahasa Inggeris paling sering diguna pakai adalah lebih mudah didapatkan. 

https://www.ef.com/english-resources/english-vocabulary/top-3000-words/
https://www.wordfrequency.info/free.asp?s=y

Jika mahu bincang lebih dalam lagi saya saran kita berjumpa... Elak isu lesen dan sebagainya. 

Takrif perkataan ambil dari mana nanti? Atau kita sendiri yang sediakan takrif?

**Comment by kmubiin** [comment]
**Maklum balas setakat petang 21 Mac (Rabu)**

> "Kosa kata yang sering diguna pakai"
>
> Saya setuju. Dalam pengalaman saya, perkataan bahasa Inggeris paling sering diguna pakai adalah lebih mudah didapatkan.

Untuk mendapatkan senarai perkataan sahaja, kita boleh kumpul daripada mana-mana sumber tidak kira sama ada hak cipta terpelihara atau tidak. Ini kerana, secara umum, senarai bahan atau kandungan semata-mata tidak dilindungi hak cipta (rujuk di https://www.copyright.gov/help/faq/faq-protect.html).

> Takrif perkataan ambil dari mana nanti? Atau kita sendiri yang sediakan takrif?

Saya sedar projek ini masih tak jelaskan bagaimana kosa kata akan tersenarai. Untuk seketika, saya keliru sama ada projek ini hendak senaraikan kosa kata sebagai 'glosari' atau 'kamus takrif penuh'?

Contoh glosari (dwibahasa):

| inggeris   | melayu       |
| ---------- | ------------ |
| water      | air          |
| chlorophyl | klorofil     |
| rice flour | tepung beras |
| ...        | ...          |

Contoh kamus takrif penuh (dwibahasa):

| inggeris   | melayu       | makna                                    |
| ---------- | ------------ | ---------------------------------------- |
| water      | air          | cecair jernih di dalam sungai dan laut   |
| chlorophyl | klorofil     | pigmen hijau di dalam daun-daun tumbuhan |
| rice flour | tepung beras | tepung daripada beras digiling halus     |
| ...        | ...          | ...                                      |

Memetik komen-komen yang berasal daripada isu 1:

> > Perincian maksud atau definisi untuk kata masukan
>
> A: Selagi boleh, takrif terpendek. Kalau satu patah perkataan, lagi bagus.

Saudara A pernah menyatakan hasrat untuk membawakan takrif terpendek. Dan lagi, e-mel bertarikh 12 Feb 2018 ada menyatakan bahawa kita mahu mencari perkataan Melayu yang mempunyai makna yang sama atau serasi mungkin dengan perkataan Inggeris yang kita guna.

Hasil perbincangan di atas mencadangkan kita akan buat 'glosari', jadi kita boleh abaikan lajur makna. Tak perlu berfikir lagi untuk dapatkan takrif yang menyentuh isu lesen.

> Jika mahu bincang lebih dalam lagi saya saran kita berjumpa... Elak isu lesen dan sebagainya.

Sebelum itu, saya mahu sediakan draf baru untuk Rancangan Pertengahan. Tanpa rancangan bertulis, saya tak dapat pastikan apa yang perlu kita bincang... Saya akan teliti semula isu ini, permudahkan cadangan M dan kenal pasti isu-isu baru dalam sehari dua ini.

**Comment by kmubiin** [comment]
**Kemas kini untuk rangkuman kosa kata**

Perkara-perkara berikut telah disemak:

> Kriteria atau cara pemilihan kosa kata

Sudah ditentukan: Kosa kata yang sering diguna pakai.

> Mata pelajaran atau bidang yang akan diteroka

Ada perubahan: Mengikut sumber tersedia yang dipilih. Bilangan bidang atau sumber tersedia akan diterhadkan kepada 2-3 bidang sahaja. Perbincangan lanjut di isu baru 'Keterbalikan antara sumber dan bidang kosa kata' (lihat pautan "referenced" yang tertimbul sebelum komen ini).

> Pecahan kata masukkan daripada jumlah 100-300
 
Ada perubahan: Mengikut sumber tersedia yang dipilih. Dari segi purata, 50-150 kata masukan untuk setiap sumber tersedia. Jika sumber tersedia mengandungi kata masukan yang lebih banyak daripada purata tersebut, maka bolehlah membuat pilihan sendiri sama ada:

* Terjemahkan kesemua perkataan dalam sumber (jika tidak melebihi had 100-300), atau
* Terjemahkan 5 perkataan dipilih secara rawak untuk setiap abjad A-Z (Ini akan membawa jumlah perkataan sebanyak 5*26 = 130), atau
* Terjemahkan 100 perkataan pilihan mengikut kriteria tersendiri

Jika mengikut kriteria tersendiri, maka sewajarnya terangkan kriteria itu supaya pendokumenan (documentation) boleh dibuat kemudian. Perbincangan lanjut juga di isu baru 'Keterbalikan antara sumber dan bidang kosa kata' (lihat pautan "referenced" yang tertimbul sebelum komen ini).

Isu ini telah disemak semula secara menyeluruh dan boleh ditutup.

**Comment by kmubiin** [comment]
Memetik komen daripada maklum balas tempoh hari:

>> Takrif perkataan ambil dari mana nanti? Atau kita sendiri yang sediakan takrif?
>
> Saya sedar projek ini masih tak jelaskan bagaimana kosa kata akan tersenarai.

Maaf, saya baru perasan ada lagi satu pandangan untuk menjawab soalan di atas.

Pandangan pertama ialah sama ada perlu ada makna atau huraian panjang untuk kata masukan yang diberi. Dengan kata lain, sama ada kita gunakan dua lajur sahaja (inggeris, melayu) atau tiga lajur (inggeris, melayu, makna). Perbincangan kita menunjukkan glosari, jadi pakai dua lajur sahaja.  

Pandangan kedua ialah apabila kata masukan tidak mempunyai perkataan jitu dalam bahasa Melayu untuk kata masukan Inggeris yang diberi. Contoh: 'panda' ialah 'panda' dalam bahasa Melayu. Jadi, lajur 'melayu' akan mengandungi takrif pendek seperti 'sejenis binatang seperti beruang'.

Agaknya pandangan kedua inilah yang dimaksudkan oleh saudara A tempoh hari? Mungkin.

> Takrif perkataan ambil dari mana nanti? Atau kita sendiri yang sediakan takrif?

Untuk menjawab semula soalan tersebut mengikut pandangan kedua, kita cari takrif terpendek daripada teks di Wikipedia (mana lagi nak cari...) untuk permulaan.

Jika tak jumpa takrif terpendek, kita ada beberapa pilihan:

A. Kita sendiri yang sediakan takrif (berusaha)
B. Kita isikan 'tidak ada terjemahan' di ruang takrif (berkecuali)
C. Kita abaikan dan pilih lain kata masukan Inggeris (bertangguh)

Saya akan cipta isu baru untuk panduan menyediakan takrif.
