### ISSUE TITLE
Keterbalikan antara sumber dan bidang kosa kata

### ISSUE THREAD

**Issue by kmubiin** [kmubiin/suaikata#7]
Berasal daripada #4 

Isu ini akan membincangkan semula mata pelajaran atau bidang yang akan diteroka, dengan cara memilih sumber tersedia terlebih dahulu.

Cara pemilihan terbalik ini adalah lebih mudah, tetapi bidang akan terhad kepada sumber tersedia yang dipilih. Perbandingan cara sebelum ini (isu 4) dan sekarang (isu ini):

* Sebelum ini: Mulanya pilih bidang, kemudian cari sumber.
* Sekarang: Pilih sumber tersedia, dan bidang terpilih mengikut sumber.

Ada beberapa ciri yang akan menentukan bidang kosa kata secara tidak langsung.

1. Kemudahan memenuhi kriteria atau cara pemilihan kosa kata
2. Kemudahan mengguna semula sumber kosa kata
3. Kemudahan mematuhi daftar kosa kata terbaru

Ciri 1 menyoal sama ada kosa kata mempunyai sumber tersedia yang memenuhi kriteria atau tidak. Jika kosa kata tidak ada sumber tersedia, misalnya untuk bidang tertentu, maka boleh cipta takrif tersendiri supaya kosa kata daripada mana-mana sumber boleh dikumpul mengikut kriteria tersebut.

Ciri 2 menyoal isu hak cipta sumber kosa kata, terutama kosa kata yang disertakan bersama takrif atau makna. Jika kosa kata bersama makna disalin semula daripada sumber hak cipta terpelihara atau sumber yang tidak disertakan lesen, maka akan timbul isu pelanggaran hak cipta.

Ciri 3 menyoal sama ada kosa kata yang dikumpul adalah terbaru atau terkini. Jika sumber kosa kata mudah didapati dan bebas diguna semula sekali pun, tetapi misalnya menggunakan ejaan lama yang tidak lagi diterima pada masa ini, maka akan timbul isu ketinggalan zaman.

Sumber tersedia yang dipilih seharusnya mengambil kira ciri-ciri di atas.

* Untuk kamus tafsiran penuh, pastikan ciri 1, 2, 3; atau
* Untuk kamus glosari, pastikan ciri 1 sudah memadai

Senarai kemas kini komen ini:

* 22 Mac: Perubahan pada cara memilih bidang kosa kata. 
* 26 Mac: Perenggan terakhir ada teks tambahan untuk penerangan.
* 6 Mei: Apabila dibaca semula, M sendiri sukar faham teks di atas.
* 7 Mei: Ulang baca dan sedang tulis semula sebagai fail dokumentasi.

**Comment by kmubiin** [comment]
**Hasil carian antara 21 Mac (Rabu) dan 26 Mac (Isnin)**

Berikut adalah sumber tersedia yang mengandungi senarai kata masukan Inggeris mengikut hasil carian setiap ahli. Hasil carian A telah disalin semula daripada komen isu 4 bersama tajuk di pautan.

Hasil carian A:

* [3000 most common words in English][a1]
* [Top 5000 words in American English][a2]

Hasil carian M:

* The Academic Word List (AWL), [570 words via Wiktionary][m1]
* [The 100 Most Common SAT Words][m2]
* [100 Science Words Every College Graduate Should Know][m3]
* [The OED's 100  Words That Define The First World War][m4] (slideshow) via [dailymail.co.uk][m5] (text)
* [PSAT High Frequency Words (1980-1999), 267 words][m6] (pautan arkib)
* [100 Words for Facial Expressions][m7]

Lebih carian di [Category:Wordlists on Wiktionary][more]

Perbincangan lanjut akan diadakan di luar talian.

Nota 1: Hasil carian M ada tambahan senarai yang tertinggal sebelum ini: PSAT  
Nota 2: Hasil carian M ada tambahan senarai baru: 100 Words for Facial Expressions  

*Disemak: Semua pautan boleh dicapai setakat 17 Mac 2020*

  [a1]: https://www.ef.com/english-resources/english-vocabulary/top-3000-words/
  [a2]: https://www.wordfrequency.info/free.asp?s=y
  [m1]: https://simple.wiktionary.org/wiki/Wiktionary:Academic_word_list
  [m2]: http://www.washingtonpost.com/wp-adv/eduadv/kaplan/kart_ug_sat100.html
  [m3]: http://www.houghtonmifflinbooks.com/booksellers/press_release/100science/
  [m4]: http://oxford.ly/ww1words
  [m5]: http://www.dailymail.co.uk/news/article-2658589/OED-launches-100-words-commemorate-centenary-First-World-War-including-demob-cushy-tooter-sweeter.html
  [m6]: https://web.archive.org/web/20170427204836/http://cabrinihigh.com/academics/psatwords
  [m7]: https://www.dailywritingtips.com/100-words-for-facial-expressions/
  [more]: https://simple.wiktionary.org/wiki/Category:Wordlists

**Comment by kmubiin** [comment]
**Hasil carian pada 27 Mac (Selasa)**

Hasil carian M untuk senarai yang lebih kecil tetapi terkini atau terpilih:

* [Collins 2017 Word of the Year Shortlist][1]
* [Top 10 Collins Words of the Year 2016][2]
* [Top 10 Collins Words of the Year][3] - Ini adalah senarai pertama pada tahun 2015
* [Beat Blue Monday with 10 words to describe happiness][4]
* [10 lost words from the Collins English Dictionary to build into everyday conversation][5]

Jumlah perkataan yang didapati: 50 perkataan.

  [1]: https://www.collinsdictionary.com/word-lovers-blog/new/collins-2017-word-of-the-year-shortlist,396,HCB.html
  [2]: https://www.collinsdictionary.com/word-lovers-blog/new/top-10-collins-words-of-the-year-2016,323,HCB.html
  [3]: https://www.collinsdictionary.com/word-lovers-blog/new/top-10-collins-words-of-the-year,259,HCB.html
  [4]: https://www.collinsdictionary.com/word-lovers-blog/new/beat-blue-monday-with-10-words-to-describe-happiness,419,HCB.html
  [5]: https://www.collinsdictionary.com/word-lovers-blog/new/10-lost-words-from-the-collins-english-dictionary-to-build-into-everyday-conversation,391,HCB.html

**Comment by kmubiin** [comment]
**Lebih hasil carian pada 27 Mac (Selasa)**

Hasil carian A yang disalin semula daripada e-mel:

* Wordfreq          word frequency perkataan inggeris dari https://www.wordfrequency.info/free.asp?s=y
* Kata-dasar              kepala entri kamus dbp edisi ke-4
* Malaycorpus       word frequency perkataan bahasa (indo/melayu) dari https://invokeit.wordpress.com/frequency-word-lists/ ^1
* Mlytop2k          top 2000 dari malaycorpus berserta google translate

Fail lampiran (attachment file) tidak disertakan ^2

**Komen M**

^1: Artikel ini sebenarnya ada pautan lain yang dituju pada repositori di GitHub: https://github.com/hermitdave/FrequencyWords/

Minggu lalu, saya sudah jumpa sumber ^1 ini dan "termuat turun" repositori seluruhnya walhal set perkataan Inggeris dan Melayu hanya 600 kB jika muat turun fail individu. Aduhai! Senarai perkataan berjela dan tidak begitu bermakna, jadi saya telah abaikan.

^2: Jika ada masa, lebih baik tampal senarai perkataan sebagai format CSV di GitHub Gist melalui akaun sendiri. Senarai perkataan tanpa makna tidak dipelihara hak cipta, jadi bebas untuk dikongsi.

**Comment by kmubiin** [comment]
**Hasil perbincangan pada 27 Mac (Selasa)**

Sumber yang dipilih ialah [PSAT High Frequency Words (1980-1999)][1].

Sebanyak 267 daftar kata Inggeris boleh didapati daripada sumber tersebut. Pilihan ini dibuat berdasarkan bilangan kata masukan terbanyak tetapi masih dalam lingkungan had yang ditetapkan, iaitu 100-300 kata masukan.

Terjemahan sumber tersebut tidak semestinya menghasilkan jumlah daftar kata yang sama, kerana satu daftar kata yang diberi (Inggeris) mungkin mempunyai lebih daripada satu makna. Daftar kata yang diterjemah (Melayu) akan membawa takrif untuk setiap makna tersebut.

Cara terjemahan untuk sumber ini adalah secara individu (manual) dan *tidak* menggunakan bantuan mesin terjemahan. Setiap ahli akan menggunakan kamus Inggeris untuk memahami takrif dalam bahasa asli (Inggeris), kemudian mencari takrif dalam bahasa terjemah (Melayu).

Pilihan sumber telah ditetapkan, maka isu ini dianggap selesai dan boleh ditutup.

Nota: Untuk menambah sumber lain, sila cipta isu baru dengan nama sumber sebagai tajuk isu.

  [1]: http://cabrinihigh.com/academics/psatwords

**Comment by raafsmakmal** [comment]
Turut dibincangkan dan dipersetujui tempoh hari:

- Saudara M akan menyediakan helai rebak googlesheet untuk kesemua perkataan dalam senarai yang 267. 
- Lajur pertama googlesheet mengandungi perkataan yang 267, lajur kedua dan ketiga mengandungi terjemahan yang bakal diisi M dan A.
- Googlesheet boleh ditambah baris (row) baru sekiranya ada terjemahan lain.
- Masukkan terjemahan mengikut kadar sendiri sehinggalah helai rebak diisi penuh.
- Hasil lengkap tak perlu dibuat front-end/aplikasi. Sekadar csv atau json dan dimuat naik ke suaikata.
- A juga akan mengusahakan terjemahan mesin untuk senarai carian A Wordfreq yang 3000. Hasil ini pun akan dimuat naik ke suaikata.

**Comment by kmubiin** [comment]
Berkenaan komen A:

> A juga akan mengusahakan terjemahan mesin untuk senarai carian A Wordfreq yang 3000. Hasil ini pun akan dimuat naik ke suaikata.

@raafsmakmal 
Ciptakan isu baru untuk hasil carian A tersebut. Lebih baik diciptakan oleh A sendiri supaya boleh kemas kini isu itu mengikut keperluan A *tanpa* pengendalian M. Sila [buka isu baru][1].

  [1]: https://github.com/kmubiin/suaikata/issues/new
