### ISSUE TITLE
Statistik data terkumpul

### ISSUE THREAD

**Issue by kmubiin** [kmubiin/suaikata#8]
Isu tak bersandar untuk menjadikan projek ini lebih menarik.

Selain bilangan kata masukan, mungkin ada butir-butir lain yang boleh dihitung seperti: 

* Bilangan kata masukan Melayu mengikut abjad
* Bilangan kata masukan Melayu mengikut satu, dua dan lebih perkataan
* Nisbah terjemahan huruf atau perkataan Inggeris-Melayu

Mana-mana butir berkenaan mungkin boleh memberi anggaran bilangan kata masukan Melayu yang tidak dijumpai untuk kata masukan Inggeris tersenarai.

Perhitungan boleh dibuat menggunakan formula dalam helaian rebak (spreadsheet) atau menulis skrip kecil dalam bahasa pengaturcaraan pilihan sendiri. Helaian rebak atau skrip yang dicipta untuk perhitungan adalah hak cipta masing-masing dan *tidak perlu* dimuat naik ke repositori projek ini.

Sekiranya kaedah perhitungan dapat diterangkan secara ringkas, itu sudah cukup baik. Memadai dengan tinggalkan komen di jalur isu ini, supaya pendokumenan (documentation) dapat dibuat dan dimuat naik ke repositori projek kemudian.

---

**28 Mac 2018**: Salah satu cadangan telah dilaksanakan dalam helaian rebak di Google Sheets. 'Daftar asal mengikut abjad' hanya mengira bilangan kosa kata Inggeris daripada sumber yang dipilih, yang hanya menggunakan bahasa Inggeris.

**29 Mac 2018**: Satu lagi carta ditambah di Google Sheets. 'Daftar terjemah mengikut abjad' mengira bilangan kosa kata Inggeris (termasuk perkataan ulangan) dan kosa kata Melayu (termasuk makna-makna untuk perkataan ulangan).

**15 April 2018**: Setiap kali kosa kata terjemah disemak dan berubah pada satu-satu masa, paparan jadual dan carta daftar semasa terjemah akan turut berubah serta-merta. Ini adalah perkara biasa. Jadi, sebarang usaha selidik lebih baik dilakukan selepas daftar tersebut telah siap dan dimuat naik ke repositori. Isu ini akan dikeluarkan daripada Rancangan Akhir dan akan bersambung kemudian.

**Comment by kmubiin** [comment]
Salah satu cadangan telah disediakan dalam helaian rebak. Tangkapan layar (screenshot) di bawah menunjukkan contoh carta yang disediakan di Google Sheets:

![daftar-psat-chart-2](https://user-images.githubusercontent.com/30212524/38043705-6fa372f0-32ea-11e8-9c26-eee7b9974203.png)

'Daftar asal mengikut abjad' hanya mengira bilangan kosa kata Inggeris daripada sumber yang dipilih, yang hanya menggunakan bahasa Inggeris. Bilangan kosa kata Melayu ialah sifar pada asalan dan hanya boleh dikira selepas terjemah menggunakan jadual dan carta baru.

**Comment by kmubiin** [comment]
Satu lagi contoh carta yang disediakan di Google Sheets:

![daftar-psat-chart-3](https://user-images.githubusercontent.com/30212524/38080358-d0350320-3373-11e8-89c4-689cb3e82608.png)

'Daftar terjemah mengikut abjad' mengira bilangan kosa kata Inggeris (termasuk perkataan ulangan) dan kosa kata Melayu (termasuk makna-makna untuk perkataan ulangan).

**Comment by kmubiin** [comment]
**Daftar terjemah mengikut abjad setakat 2 April 2018 (Isnin)**

![daftar-psat-carta-3-77](https://user-images.githubusercontent.com/30212524/38204417-7b6feb06-36d5-11e8-927e-0029c565dfda.png)

Pemerhatian semasa:

* Carta menunjukkan taburan apabila 77/265 kosa kata asal Inggeris telah diterjemah.
* Abjad `e`, `g`, `i`, `n`, `o`, `u`, `v`, `w` mengumpul hanya kosa kata terjemah Inggeris.
* Abjad `j`, `k` mengumpul hanya kosa kata terjemah Melayu.
* Abjad `q`, `x`, `y`, `z` langsung tidak mengumpul apa-apa kosa kata.
* Abjad selebihnya mengumpul kosa kata terjemah Inggeris dan Melayu.

**Comment by kmubiin** [comment]
**Daftar terjemah mengikut abjad setakat 6 April 2018 (Jumaat)**

![daftar-psat-carta-3-135](https://user-images.githubusercontent.com/30212524/38408422-0b933166-39b0-11e8-9ee3-81f66847a674.png)

Pemerhatian semasa:

* Carta menunjukkan taburan apabila 135/265 kosa kata asal Inggeris telah diterjemah.
* Abjad `e`, `u`, `v` mengumpul hanya kosa kata terjemah Inggeris (tidak berubah).
* Abjad `j`, `k` mengumpul hanya kosa kata terjemah Melayu (tidak berubah).
* Abjad `q`, `x`, `y`, `z` langsung tidak mengumpul apa-apa kosa kata (tidak berubah).
* Abjad `g`, `i`, `n`, `o`, `w` dahulu mengumpul hanya kosa kata terjemah Inggeris, sekarang sudah mula mengumpul kosa kata terjemah Melayu.
* Abjad `a`, `b`, `k`, `m`, `p`, `s`, `t` mengalami kenaikan mendadak untuk kosa kata terjemah Melayu, barangkali sebab gunakan imbuhan di hadapan kata dasar, dan diiringi kata 'ada' dan 'tiada'.
* Abjad selebihnya mengumpul kosa kata terjemah Inggeris dan Melayu.

**Comment by kmubiin** [comment]
Setiap kali kosa kata terjemah disemak dan berubah pada satu-satu masa, paparan jadual dan carta daftar semasa terjemah akan turut berubah serta-merta. Ini adalah perkara biasa. Jadi, sebarang usaha selidik lebih baik dilakukan selepas daftar tersebut telah siap dan dimuat naik ke repositori.

Isu ini akan dikeluarkan daripada Rancangan Akhir dan akan bersambung kemudian.

**Comment by kmubiin** [comment]
Fail dokumentasi baru mungkin akan dicipta untuk mengandungi maklumat seperti ini. Yakni, maklumat perangkaan untuk mana-mana hasil daftar yang disiapkan di repositori projek. Ini bermaksud, maklumat perangkaan juga boleh dilayari melalui GitHub Pages nanti.

**Comment by raafsmakmal** [comment]
Untuk halaman utama, saya sarankan kita guna perkataan buzzword/keyword yg bukan saja berkait dgn projek, malah sohor utk zaman sekarang.

Sebagai contoh:

Penerangan tentang daftar psat ada cerita tentang SAT - boleh jadi sebab kenapa dipilih perkataan SAT, apa itu SAT, tahap SAT itu bagaimana dsb. Dalam bayangan saya, spt ini:

"Daftar ini ialah terjemahan [beberapa ratus] perkataan yang biasa timbul dalam peperiksaan SAT (panjangnya Scholastic Aptitude Test, Ujian Kecenderungan Pembelajaran)... "

Utk penerangan daftar terjemahan perkataan bahasa Inggeris paling biasa ke dalam Bahasa Melayu, saya akan kemukakan penerangan untuk kita teliti bersama.

**Comment by kmubiin** [comment]
Komen baru M selepas komen yang dipetik daripada komen A dan M sebelum ini.

> A: Untuk halaman utama, saya sarankan kita guna perkataan buzzword/keyword yg bukan saja berkait dgn projek, malah sohor utk zaman sekarang.

Di mana "halaman utama" yang dimaksudkan? Saya anggap halaman utama di repositori GitHub (https://github.com/kmubiin/suaikata) yang ada tetapan "Add topics" di bawah nama umum. Tapi pelik juga kalau "buzzword/keyword" yang dimaksudkan adalah "topics" di GitHub (https://github.com/topics)...

> A: Sebagai contoh: Penerangan tentang daftar psat ada cerita tentang SAT [...]

...dan contoh yang diberi dalam perenggan seterusnya macam menerangkan perkara lain daripada komen di perenggan sebelumnya? Agak keliru.

> M: Fail dokumentasi baru mungkin akan dicipta untuk mengandungi maklumat seperti ini. Yakni, maklumat perangkaan untuk mana-mana hasil daftar yang disiapkan di repositori projek [...]

~Berkenaan fail dokumentasi yang disebutkan oleh M sebelum ini, selain maklumat perangkaan, ulasan daftar juga akan diperkenal sebagai fail dokumentasi baru dalam folder yang berasingan. [...]~ lapuk

~Maklumat angka dan ulasan telah ditulis semula sebagai dokumentasi kajian~ lapuk

**Comment by kmubiin** [comment]
Enam bulan kemudian, isu "Statistik data terkumpul" ini telah disemak semula.

Hakikatnya, maklumat perangkaan (MPA) sudah mengira bilangan kata masukan dan terjemah. Semasa pembaikan keluaran pertama, M telah menambah kebolehan menyalin maklumat perangkaan sebagai jadual Markdown melalui formula di helaian rebak.

Kemas kini maklumat perangkaan sekarang menjadi mudah dengan hanya salin dan tampal (copy and paste) maklumat itu dari helaian rebak ke fail berkenaan di GitHub.

Sebaliknya, statistik data terkumpul (SDT) mudah lapuk apabila terjemah berubah dari semasa ke semasa. SDT melibatkan pengiraan data dan penghasilan carta. Usaha mentafsirkan carta akan mengambil masa yang lebih lama. Dengan itu, kemas kini menjadi lebih leceh berbanding MPA.

Kesimpulannya, SDT *tidak akan diusahakan* kerana MPA sudah memadai.

Nota: Singkatan MPA dan SDT hanya digunakan untuk meringkaskan ayat dalam komen ini dan bukan singkatan rasmi.

**Comment by kmubiin** [comment]
Dalam hal lain, berkenaan komen A di atas:

> Penerangan tentang daftar psat ada cerita tentang SAT - boleh jadi sebab kenapa dipilih perkataan SAT, apa itu SAT, tahap SAT itu bagaimana dsb [...]

Penerangan tersebut boleh ditambah di laman kajian. Sebagai contoh, A mungkin terfikir untuk menulis tiga jenis ulasan:

1. tentang PSAT atau SAT
2. tentang daftar PSAT itu sendiri
3. tentang kata masukan dari mana-mana daftar

Maka `fail baru` dengan nama yang sesuai mungkin dicipta di lokasi berikut:

1. docs/kajian/hurai/`psat.1.md`
2. docs/kajian/hurai/`psat.a.md`
3. docs/kajian/hurai/kata/`foo.md`

Sejak pembaikan keluaran pertama, kajian daftar PSAT memuatkan beberapa tajuk kecil termasuk "ulasan pembangun daftar". Pada masa komen ini ditulis, kajian daftar PSAT mengandungi:

> Ulasan pembangun daftar
> 
> * [Ulasan M untuk daftar PSAT][0] (siap 1/12)
> * Ulasan A belum ditulis buat masa ini

Apabila mengambil kira contoh "tiga jenis ulasan" di atas, kajian daftar PSAT mungkin menjadi:

> Ulasan pembangun daftar
> 
> * [Fakta PSAT][0] <-- 1
> * [Ulasan M untuk daftar PSAT][0] (siap 1/12)
> * [Ulasan A untuk daftar PSAT][0] <--2

dan laman di pautan 2 mungkin menjadi:

> Ulasan A untuk daftar PSAT
>
> * [foo][0] <-- 3

*Semua pautan di atas adalah sekadar bayangan dan bukan pautan sebenar.*

Untuk memahami jenis ulasan "3. tentang kata masukan dari mana-mana daftar", sila rujuk pada "Ulasan M untuk daftar PSAT" di pautan sebenar [kajian daftar PSAT][1].

  [0]: #
  [1]: https://github.com/kmubiin/suaikata/blob/master/docs/kajian/psat.md

**Comment by kmubiin** [comment]
Isu lama ini akan dikunci. Sebarang hal tertangguh dalam isu ini, termasuk [komen A di atas][1], akan dibawa ke isu semasa yang dirujuk: **Ulasan pembangun daftar pertama #20**

  [1]: #issuecomment-386223659
